### ISSUE TITLE
Question about the KITTI dataset

### ISSUE THREAD

**Issue by SilvesterYu** [KamilZywanowski/MinkLoc3D-SI#3]
Hi, just wanted to ask which version of the KITTI dataset are you using? Could I have the link to the raw data which you used in your paper? Thanks in advance!

**Comment by KamilZywanowski** [comment]
Hi, following the guideline that we received from the author of MinkLoc++ we used the KITTI_00 sequence from the odometry benchmark that you can find here: [http://www.cvlibs.net/datasets/kitti/eval_odometry.php](http://www.cvlibs.net/datasets/kitti/eval_odometry.php). The pickles used for evaluation are available in the eval/ folder.

**Comment by SilvesterYu** [comment]
Thanks. Are you referring to the **2011_10_03_drive_0027** dataset in this link? http://www.cvlibs.net/datasets/kitti/raw_data.php?type=residential If so, which version is it? unsynced+unrectified data, synced+rectified data, or calibration?

**Comment by KamilZywanowski** [comment]
No, you can download all the sequences (00-21) from here: http://www.cvlibs.net/datasets/kitti/eval_odometry.php - use the 
"Download odometry data set (velodyne laser data, 80 GB)" and "Download odometry ground truth poses (4 MB)" links to get the data for all the sequences. Out of them we only used the KITTI_00 sequence for evaluation.
