### ISSUE TITLE
Local performance not matching the result in the paper

### ISSUE THREAD

**Issue by artisticengineerpi** [KamilZywanowski/MinkLoc3D-SI#4]
Hi, I tried training the model on the USyd dataset locally and evaluated using the trained weights. I trained using the command in your README and evaluated using
`python evaluate.py --config ../config/config_usyd.txt --model_config ../models/minkloc_config.txt --weights ../weights/model_MinkFPN_GeM_20220613_1608_final.pth`
And this is the result I got
![image](https://user-images.githubusercontent.com/15011271/173429712-159c1e91-6f46-4e55-91c0-e248bc2b4f2b.png)
It differs quite a lot from the result obtained by using your pre-trained weights, which was 98.98. 

Can I know whether or not the config files in config/ and the model/ folders are the optimal configuration? Thanks.

**Comment by KamilZywanowski** [comment]
Hi, yes, these are the configuration files that we used to obtain the results published in the paper. It seems like the embeddings collapsed during your training. One thing that comes to my mind is dscribed here: https://github.com/jac99/MinkLoc3D/issues/2, hope it helps.

**Comment by artisticengineerpi** [comment]
Thanks for the reply. I tried reinstalling bitarray 1.6.0 as suggested, but the performance stayed the same. Could there be other possibilities?

**Comment by KamilZywanowski** [comment]
Did you delete the _cached pickle files after reinstalling bitarray and before running the training script again?

**Comment by artisticengineerpi** [comment]
Yes I deleted. 😜

**Comment by KamilZywanowski** [comment]
Unfortunately I don't know what can be the reason - I just repeated the training with the code from git and got almost exactly the same results as with the available pre-trained weights. I used Python 3.8, PyTorch 1.7.1, MinkowskiEngine 0.5.0 on Ubuntu 18.04 with CUDA 11.0 and GeForce RTX 3080.

**Comment by artisticengineerpi** [comment]
Hello, we retried installing the correct version of bitarray and it is now resolved.
