### ISSUE TITLE
Reproducing MinkLoc3D-S results on Oxford dataset

### ISSUE THREAD

**Issue by mgladkova** [KamilZywanowski/MinkLoc3D-SI#5]
Hi @KamilZywanowski,

first of all, thanks a lot for your great work! 

I would like to reproduce the results from your paper (table III) for MinkLoc3D-S model on the submap data created by the PointNetVLAD authors. Would it be possible for you to provide a configuration file that you have used for model training? Many thanks in advance!

Cheers,
Mariia

**Comment by KamilZywanowski** [comment]
Hi, the dataset configuration file is available here: https://github.com/KamilZywanowski/MinkLoc3D-SI/blob/master/config/config_baseline.txt, and the model configuration file is:

`# MinkLoc3D model`
`[MODEL]`
`model = MinkFPN_GeM`
`version = MinkLoc3D-S`
`mink_quantization_size = 0.1,2.0,2.0`
`planes = 32,64,64`
`layers = 1,1,1`
`num_top_down = 1`
`conv0_kernel_size = 5`
`feature_size = 256`

Hope this helps,
Kamil

**Comment by mgladkova** [comment]
Thank you very much, Kamil, for your prompt reply! It was very helpful to reproduce your results.

Cheers,
Mariia
